[project]
name = "mlpype-matplotlib"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "Matplotlib extension for MLpype"

requires-python = ">=3.9"
version = "0.6.8"
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base==0.6.8",
    "matplotlib>=3.7.5",
    "numpy>=1.26.4",
    "pandas>=1.5.3",
    "shap>=0.46.0"
]

[project.optional-dependencies]
strict = [
    "matplotlib==3.7.5",
    "numpy==1.26.4",
    "pandas==1.5.3",
    "shap==0.46.0"
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mlpype"]

[tool.black]
line-length = 120