[project]
name = "mlpype-tensorflow"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "Tensorflow extension for MLpype"

requires-python = ">=3.9"
dynamic = ["version"]
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base",
    "tensorflow>=2.14.1",
    "numpy>=1.26.4",
    "protobuf>=3.20.3",
    "tensorflow-macos>=2.14.1 ; sys_platform == 'darwin'",
]

[project.optional-dependencies]
strict = [
    "tensorflow==2.14.1",
    "numpy==1.26.4",
    "protobuf==3.20.3",
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mlpype"]

[tool.black]
line-length = 120

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
latest-tag = true
pattern = '(?P<base>\d+\.\d+\.\d+)'
format = "{base}"