[project]
name = "mlpype-tensorflow"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "Tensorflow extension for MLpype"

requires-python = ">=3.9"
version = "0.6.7"
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base==0.6.7",
    "tensorflow==2.14.1",
    "numpy==1.26.4",
    "protobuf==3.20.3",
    "tensorflow-macos==2.14.1 ; sys_platform == 'darwin'",
]

[project.optional-dependencies]
strict = [
    "tensorflow==2.14.1",
    "numpy==1.26.4",
    "protobuf==3.20.3",
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["**.yaml", "**.yml"]

[tool.black]
line-length = 120