[project]
name = "mlpype-mlflow"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "MLflow extension for MLpype"

requires-python = ">=3.9"
dynamic = ["version"]
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base",
    "mlflow>=2.17.0",
    "GitPython>=3.1.27",
]

[project.optional-dependencies]
strict = [
    "mlflow==2.17.0",
    "GitPython==3.1.27",
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mlpype"]

[tool.black]
line-length = 120

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
latest-tag = true
pattern = '(?P<base>\d+\.\d+\.\d+)'
format = "{base}"