[project]
name = "mlpype-mlflow"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "MLflow extension for MLpype"

requires-python = ">=3.9"
version = "0.6.8"
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base==0.6.8",
    "mlflow>=2.17.0",
    "GitPython>=3.1.27",
]

[project.optional-dependencies]
strict = [
    "mlflow==2.17.0",
    "GitPython==3.1.27",
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mlpype"]

[tool.black]
line-length = 120