[project]
name = "mlpype-sklearn"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "Sklearn extension for MLpype"

requires-python = ">=3.9"
dynamic = ["version"]
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base",
    "numpy>=1.26.4",
    "scikit-learn>=1.2.2",
    "pandas>=1.5.3",
    "dill>=0.3.8",
]

[project.optional-dependencies]
strict = [
    "numpy==1.26.4",
    "scikit-learn==1.2.2",
    "pandas==1.5.3",
    "dill==0.3.8",
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mlpype"]

[tool.black]
line-length = 120

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
latest-tag = true
pattern = '(?P<base>\d+\.\d+\.\d+)'
format = "{base}"