[project]
name = "mlpype-sklearn"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "Sklearn extension for MLpype"

requires-python = ">=3.9"
version = "0.6.7"
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base==0.6.7",
    "numpy>=1.26.4",
    "scikit-learn>=1.2.2",
    "pandas>=1.5.3",
    "dill>=0.3.8",
]

[project.optional-dependencies]
strict = [
    "numpy==1.26.4",
    "scikit-learn==1.2.2",
    "pandas==1.5.3",
    "dill==0.3.8",
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["**.yaml", "**.yml"]

[tool.black]
line-length = 120