[project]
name = "mlpype-base"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "Base package for standardised machine learning"
readme = "README.md"
requires-python = ">=3.9"
version = "0.6.4"
license = {file = "../../LICENCE.txt"}

dependencies = [
    "docstring_parser>=0.14.1",
    "pydantic>=1.10.7",
    "joblib>=1.1.1",
    "PyYAML==6.0.1",
    "jinja2==3.1.5",
]

[project.optional-dependencies]
strict = [
    "docstring_parser==0.14.1",
    "pydantic==1.10.7",
    "joblib==1.1.1",
    "PyYAML==6.0.1",
    "jinja2==3.1.5",
]


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["**.yaml", "**.yml"]
