[project]
name = "mlpype-hyperopt"
authors = [
    {name = "Jeroen van den Hoven"},
]
description = "HyperOPT extension for MLpype"

requires-python = ">=3.9"
version = "0.6.5"
license = {"text" = "MIT"}

dependencies = [
    "mlpype-base==0.6.5",
    "hyperopt>=0.2.7"
]

[project.optional-dependencies]
strict = [
    "mlpype-base==0.6.5",
    "hyperopt==0.2.7"
]

[tool.uv.sources]
mlpype-base = { workspace = true }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["**.yaml", "**.yml"]
